dataset:
  hf_home: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets
  hf_cache: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/hf_cache
  parquet_path: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/parquet/noptm_baseline_small
  processed_path: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/processed/noptm_baseline_small_bs1024_unmod
  seq_length: 30
  batch_size: 1024
  alphabet: ALPHABET_UNMOD