dataset:
  hf_home: /cmnfs/proj/bmpc_dlomix/datasets
  hf_cache: /cmnfs/proj/bmpc_dlomix/datasets/hf_cache
  parquet_path: /cmnfs/proj/bmpc_dlomix/oktoberfest_output/refinement_etd_out/data/dlomix/refinement_dataset/processed_dataset.parquet
  processed_path: /cmnfs/proj/bmpc_dlomix/datasets/processed/oktoberfest_etd
  seq_length: 30
  batch_size: 1024
  alphabet: "ALPHABET_NAIVE_MODS"
  new_mods: ["S[UNIMOD:21]"]
  val_ratio: 0.2
  test_ratio: 0.1
processing:
  num_proc: 20
