dataset:
  hf_home: /cmnfs/proj/bmpc_dlomix/datasets
  hf_cache: /cmnfs/proj/bmpc_dlomix/datasets/hf_cache
  parquet_path: /cmnfs/home/students/j.schlensok/oktoberfest/tutorials/out2/data/dlomix/refinement_dataset/processed_dataset.parquet
  processed_path: /cmnfs/proj/bmpc_dlomix/datasets/processed/refinement_dataset_toy_orig_seq
  seq_length: 30
  batch_size: 1024
  alphabet: PTMS_ALPHABET
  val_ratio: 0.1 
  test_ratio: 0.1 