dataset:
  hf_home: /cmnfs/proj/bmpc_dlomix/datasets
  hf_cache: /cmnfs/proj/bmpc_dlomix/datasets/hf_cache
  parquet_path: /cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/no_aug
  processed_path: /cmnfs/proj/bmpc_dlomix/datasets/processed/ptm_baseline_full_bs1024
  seq_length: 30
  batch_size: 1024
  alphabet: PTMS_ALPHABET