dataset:
  hf_home: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets
  hf_cache: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/hf_cache
  parquet_path: /cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/clean
  processed_path: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/processed/ptm_baseline_small_bs1024
  seq_length: 30
  batch_size: 1024
  alphabet: PTMS_ALPHABET