dataset:
  hf_home: /cmnfs/proj/bmpc_dlomix/datasets
  hf_cache: /cmnfs/proj/bmpc_dlomix/datasets/hf_cache
  parquet_path: /cmnfs/proj/bmpc_dlomix/datasets/parquet/transfer_learning_toy_dataset/new_modification
  processed_path: /cmnfs/proj/bmpc_dlomix/datasets/processed/new_modification
  seq_length: 30
  batch_size: 1024
processing:
  num_proc: 40