# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
  # Build the rst files in case API has changed or modules has been added
    pre_build:
    # M Modules first, E no headers, f force overwrite, l links, o output directory
      - sphinx-apidoc -M -E -f -l -o docs/ src/dlomix/
      - python docs/codify_package_titles.py
    build:
      html:
        - make build-docs
        - echo '<html><head><meta http-equiv="refresh" content="0; url=tensorflow/index.html"></head></html>' > docs/_build/html/index.html
      pdf:
        - echo "Skipping PDF build"
      epub:
        - echo "Skipping EPUB build"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
