dataset:
  name: noptm_baseline_small_bs1024
  hf_home: /cmnfs/proj/bmpc_dlomix/datasets
  hf_cache: /cmnfs/proj/bmpc_dlomix/datasets/hf_cache
  parquet_path: /cmnfs/proj/bmpc_dlomix/datasets/parquet/noptm_baseline_small
  processed_path: /cmnfs/proj/bmpc_dlomix/datasets/processed/noptm_baseline_small_bs1024
  seq_length: 30
  batch_size: 1024
  alphabet: PTMS_ALPHABET
training:
  learning_rate: 0.001
  num_epochs: 60
  early_stopping:
    min_delta: 0.0001
    patience: 8
  lr_scheduler_plateau:
    cooldown: 1
    factor: 0.5
    min_delta: 0.0001
    patience: 2
  lr_warmup_linear:
    num_epochs: 10
    start_lr: 0.00001
    end_lr: 0.001
model:
  save_dir: /cmnfs/proj/bmpc_dlomix/models/baseline_models
