dataset:
  name: noptm_baseline_full_bs1024_smallalphabet
  hf_home: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets
  hf_cache: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/hf_cache
  parquet_path: /cmnfs/data/proteomics/Prosit_unmod/intensity/no_aug
  processed_path: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/processed/noptm_baseline_full_bs1024_smallalphabet
  seq_length: 30
  batch_size: 1024
  alphabet: ALPHABET_UNMOD
training:
  learning_rate: 0.001
  num_epochs: 60
  early_stopping:
    min_delta: 0.00001
    patience: 8
  lr_warmup_linear:
    num_epochs: 6
    start_lr: 0.00001
    end_lr: 0.001
model:
  save_dir: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/models/baseline_models