dataset:
  hf_home: /cmnfs/proj/bmpc_dlomix/datasets
  hf_cache: /cmnfs/proj/bmpc_dlomix/datasets/hf_cache
  parquet_path: /cmnfs/data/proteomics/Prosit_PTMs/Transformer_Train/clean
  processed_path: /cmnfs/proj/bmpc_dlomix/datasets/processed/baseline_dataset_small_bs1024
  seq_length: 30
  batch_size: 1024
  alphabet: PTMS_ALPHABET
training:
  learning_rate: 1.0e-4
  num_epochs: 1
