dataset:
  name: noptm_baseline_small_bs1024
  hf_home: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets
  hf_cache: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/hf_cache
  parquet_path: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/parquet/noptm_baseline_small
  processed_path: /cmnfs/proj/prosit_astral/bmpc_dlomix_group/datasets/processed/noptm_baseline_small_bs1024
  seq_length: 30
  batch_size: 1024
training:
  learning_rate: 1.0e-4
  num_epochs: 1
model:
  save_path: /cmnfs/home/f.kapitza/dlomix/finn_notebooks/models/test.keras