dataset:
  name: ETD_from_scratch
  hf_home: /cmnfs/proj/bmpc_dlomix/datasets
  hf_cache: /cmnfs/proj/bmpc_dlomix/datasets/hf_cache
  parquet_path: /cmnfs/proj/bmpc_dlomix/oktoberfest_output/refinement_etd_out/data/dlomix/refinement_dataset/processed_dataset.parquet
  processed_path: /cmnfs/proj/bmpc_dlomix/datasets/processed/oktoberfest_etd
  seq_length: 30
  batch_size: 1024
  alphabet: "ALPHABET_NAIVE_MODS"
  new_mods: ["S[UNIMOD:21]"]
  val_ratio: 0.2
  test_ratio: 0.1
project: "ETD_refinement_final"
training:
  learning_rate: 0.0001
  num_epochs: 10000
  early_stopping:
    min_delta: 0.00001
    patience: 10
  lr_scheduler_plateau:
    cooldown: 1
    factor: 0.5
    min_delta: 0.0001
    patience: 4
model: 
processing:
  num_proc: 20
  cuda_device_nr: "2"
model:
  save_dir: /cmnfs/proj/bmpc_dlomix/models/refinement_transfer_learning/etd_models