dataloader:
  dataset: full
  batch_size: 1024
  save_path: /cmnfs/proj/prosit_astral/datasets/parquet
model_settings:
  prec_type: inject_pre
train_settings:
  lr_base: 1.0e-4
  lr_method:
  epochs: 1

